Repository mavend/octoboard, pull requests merged in 2021-03, with the labels that each got.

#151 Allow running app locally
  .firebaserc
  .gitignore
  README.md
  firebase.json
  package-lock.json
  package.json
  src/services/Auth.js
  src/services/DataStore.js
  src/services/Firebase.js
Labels: enhancement

#171 Fix FireStore emulator initialisation
  src/services/DataStore.js
Labels: bug

#156 Add languages and categories selection to Kalambury
  public/locales/en/kalambury.json
  public/locales/en/translation.json
  public/locales/pl/kalambury.json
  public/locales/pl/translation.json
  src/components/game/Chat/Chat.js
  src/components/lobby/CreateMatchForm.js
  src/games/kalambury/Board/SettingsBoard.js
  src/games/kalambury/Board/index.js
  src/games/kalambury/Game.js
  src/games/kalambury/data/phrases/en/easy.json
  src/games/kalambury/data/phrases/en/hard.json
  src/games/kalambury/data/phrases/en/index.js
  src/games/kalambury/data/phrases/en/medium.json
  src/games/kalambury/data/phrases/index.js
  src/games/kalambury/data/phrases/pl/easy.json
  src/games/kalambury/data/phrases/pl/index.js
Labels: enhancement

#229 Redesign lobby
  public/locales/en/lobby.json
  public/locales/pl/lobby.json
  src/components/game/LeaveButton.js
  src/components/lobby/MatchItem.js
  src/components/lobby/MatchItem.module.css
  src/components/lobby/MatchesList.js
  src/games/kalambury/Board/index.js
Labels: enhancement, preview-deploy

#230 Allow setting custom match name
  public/locales/en/lobby.json
  public/locales/pl/lobby.json
  src/components/layout/GameLayout.js
  src/components/lobby/CreateMatchForm.js
  src/components/lobby/CreateMatchForm.module.css
  src/components/lobby/MatchItem.js
  src/utils/generators/locales/en.json
  src/utils/generators/locales/pl.json
  src/utils/generators/names.js
Labels: preview-deploy

#243 Add lobby filtering
  public/locales/en/lobby.json
  public/locales/pl/lobby.json
  src/components/lobby/FilterBox.js
  src/components/lobby/FilterBox.module.scss
  src/components/lobby/Lobby.js
  src/components/user/UserMenu.js
Labels: preview-deploy

#247 Add Sentry
  .github/workflows/deploy-master.yml
  .github/workflows/deploy-pull-request.yml
  app.yaml
  package-lock.json
  package.json
  public/images/hugo-fatal-error.png
  src/App.js
  src/components/lobby/CreateMatchForm.js
  src/index.js
  src/server.js
  src/services/Airbrake.js
  src/services/ErrorBoundary.js
  src/services/Sentry.js
  src/views/ErrorPage.js
Labels: preview-deploy
